FROM ghcr.io/cross-rs/arm-unknown-linux-gnueabihf:main

RUN dpkg --add-architecture armhf && \
    printf "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports focal main universe\n" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get install --assume-yes libdbus-1-dev:armhf pkg-config
